### ISSUE TITLE
Do 11. 4. vytvořit dokument analýzy a návrhu.

### ISSUE THREAD

**Issue by msebela** [ZSWI-MaLuHo/zswi-scenare#5]
Dokument analýzy a návrhu bude obsahovat:
- kontextový diagram, resp. diagram nasazení - vytvořit diagram, ve kterém budou popsány (i textově) jednotlivé komponenty a jejich propojení (popsat technicky)
- seznam a popis scénářů, které budeme přepisovat a popsání každého z nich (napsat, co se v nich děje, kód nevkládat)

**Comment by msebela** [comment]
Na datum 6. 4. od 11.00 do 12.00 rezervována laboratoř UN 323, viz Google Kalendář. Zjistíme podrobnosti, které pak zaneseme do požadovaného diagramu a informace o scénářích.

**Comment by jirmanj** [comment]
Do sekce _Wiki - Dokument analýzy a návrhu_ jsem doplnil několik údajů, které chyběly v původním dokumentu.

**Comment by jelinklu** [comment]
Grafické schéma zapojení komponent jsem vytvořila.

**Comment by msebela** [comment]
Uzavírám se získaným výsledkem 10 bodů z 10.
