### ISSUE TITLE
27. 4. Instalace OpenSesame + synchronizace

### ISSUE THREAD

**Issue by msebela** [ZSWI-MaLuHo/zswi-scenare#8]
Nainstalovat OpenSesame na PC v UN-323, provést nutná nastavení, vyzkoušet přepsané scénáře, zkontrolovat synchronizaci. Laboratoř zarezervována na čtvrtek 27. 4. od 9.00 do 13.00.

**Comment by msebela** [comment]
**Po instalace v UN-323:**
Odkaz na plugin pro podporu paralelního portu do OpenSesame: http://osdoc.cogsci.nl/3.1/manual/devices/parallel/
Pozor, poslední verze pluginu 6.0 po vyzkoušení nefunguje - zde je odkaz na starší verze (verze 5.0 byla funkční v UN-323): https://github.com/dev-jam/opensesame_plugin_-_parallel_port_trigger/releases

**Comment by jirmanj** [comment]
Pro upřesnění bych zde napsal odkaz, kde najít návod pro instalaci pluginu:
http://osdoc.cogsci.nl/3.1/manual/environment/
..nejjednodušší návod v sekci: Manually installing plugins and extensions
